version: 1
workers:
- name: esp32
  checks:
  - cmd:
    - pwd
  - cmd:
    - /home/sw/gohci/esp32-build.sh
  - cmd:
    - /home/sw/gohci/esp32-basics.sh
- name: u3
  checks:
  - cmd:
    - pwd
  - cmd:
    - /home/sw/gohci/stm32-build.sh
  - cmd:
    - /home/sw/gohci/stm32-basics.sh
