version: 1
workers:
- name: gohci-u3
  checks:
  - cmd:
    - date
  - cmd:
    - git
    - describe
    - --dirty
    - --always
  - cmd:
    - /home/gohci/esp32-build.sh
  - cmd:
    - /home/gohci/esp32-full.sh
  - cmd:
    - /home/gohci/stm32-build.sh
  - cmd:
    - /home/gohci/stm32-full.sh
